```yaml
#=====================================================================================
# Build the Docker image of OpenWrt
# Repository: https://github.com/kiloon/amlogic-openwrt
#=====================================================================================

name: Build the Docker image of OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Select the source branch"
        required: false
        default: "lede"
        type: choice
        options:
          - lede
          - official

      docker_img:
        description: "Set the Docker image"
        required: false
        default: "ophub/openwrt-aarch64:latest"
        type: string

      push_to_dockerhub:
        description: "Push image to Docker Hub"
        required: false
        default: false
        type: boolean

permissions:
  contents: read

env:
  TZ: America/New_York
  MAKE_DOCKER_SH: config-openwrt/docker/make_docker_image.sh
  DOCKER_OUTPATH: out

jobs:
  build:

    runs-on: ubuntu-22.04

    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:

      # --------------------------------------------------------------------------
      # Checkout repositor
```
